<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 5
        spacing: 5
        Image:
            id: img
        TextInput:
            id: user_search
            multiline: False
            size_hint_y: 0.1
        Button:
            text: "Search Image"
            size_hint_y: 0.1
            on_press: root.preview_img()

<RootWidget>:
    FirstScreen:
        id: first_screen
        name: "first_screen"